# Where should we write the GIF?
Output overview.gif

Set FontFamily "FiraCode Nerd Font"
Set PlaybackSpeed 0.2
Set Padding 0
Set FontSize 24
Set Width 1600
Set Height 1000
Set Theme "iTerm2 Solarized Dark"

Type "./docker-dash --docker.host ssh://geekom"
Enter
Sleep 2

Type "?"
Sleep 3
Type "?"

Type "d"
Sleep 3
Type "n"

Right@500ms 1
Sleep 3
Tab
Sleep 2
Down
Down
Down
Down
Sleep 2
Tab
Type "]"
Sleep 2
Type "]"
Sleep 5
Type "]"
Sleep 10
Right@500ms 2
Sleep 5

Hide
Ctrl+C
