# Where should we write the GIF?
Output overview.gif

Set FontFamily "FiraCode Nerd Font"
Set PlaybackSpeed 0.2
Set Padding 0
Set FontSize 24
Set Width 1600
Set Height 1000
Set Theme "iTerm2 Solarized Dark"

Type "./docker-dash"
Enter
Sleep 2

Type "?"
Sleep 3
Type "?"

Down@500ms 2
Sleep 1
Type "l"
Sleep 5

Right@500ms 1
Sleep 3
Type "?"
Sleep 2
Type "l"
Sleep 4
Type "t"
Sleep 10
Type@500ms "j"
Type@500ms "j"
Type@500ms "j"
Sleep 5
Type "?"

Hide
Ctrl+C
